# Step 1: Build frontend
FROM node:20 AS build

WORKDIR /app
COPY . .
RUN npm install && npm run build

# Step 2: Serve with NGINX
FROM nginx:stable-alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx/templates/default.conf.template /etc/nginx/templates/default.conf.template

CMD ["nginx", "-g", "daemon off;"]