FROM maven:3.9.9-eclipse-temurin-22 AS build
WORKDIR /app

COPY pom.xml .
RUN mvn -q -Pproduction -DskipTests dependency:go-offline

COPY . .
RUN mvn -q -Pproduction -DskipTests package

FROM eclipse-temurin:22-jre
WORKDIR /app
COPY --from=build /app/target/api-watchdog.jar app.jar

EXPOSE 8080
CMD ["java", "-jar", "app.jar"]
